title: "Please type your title here"
labels: ["General Introduction"]
body:
  - type: textarea
    id: Achieve
    attributes:
      label: What do you want to achieve?
      description: "Please describe  "
      value: |   
      render: bash
    validations:
      required: true

     