title: "Title"
labels: ["title"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the entire template to support you best
  - type: textarea
    id: what
    attributes:
      label: What do you want to do?
      description: "Please describe what you want to do?"
      value: |
        Please try clearly to descirbe what you want to achieve.
      render: bash
    validations:
      required: true
  - type: textarea
    id: checks
    attributes:
      label: steps
      description: "Describe the steps you have taken"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: "What is the expected results?"
      value: |
        What is your expected result
      render: bash
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Result
      description: "What is the results?"
      value: |
        What happened
      render: bash
    validations:
      required: true