title: "Title"
labels: ["title"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the entire template to support you best
  - type: textarea
    id: what
    attributes:
      label: What do you want to do?
      description: "Please describe what you want to do?"
      value: |
        Please try clearly to descirbe what you want to achieve.
      render: bash
    validations:
      required: true
  - type: textarea
    id: checks
    attributes:
      label: steps
      description: "Describe the steps you have taken"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: checks
    attributes:
      label: expected
      description: "What is the expected result?"
      value: |
        Please try to clearly describe what you expect.        
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
